/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AssortimentItem: typeof import('./src/components/AssortimentItem/AssortimentItem.vue')['default']
    AssortmentIteml: typeof import('./src/components/AssortimentItem/AssortmentIteml.vue')['default']
    Button: typeof import('primevue/button')['default']
    CardItem: typeof import('./src/components/CardItem/CardItem.vue')['default']
    CardItemInteractive: typeof import('./src/components/CardItem/CardItemInteractive.vue')['default']
    Carousel: typeof import('primevue/carousel')['default']
    CarouselItem: typeof import('./src/components/SwiperlItem/CarouselItem.vue')['default']
    ColorPicker: typeof import('primevue/colorpicker')['default']
    Drawer: typeof import('primevue/drawer')['default']
    FiltersItem: typeof import('./src/components/AssortimentItem/FiltersItem/FiltersItem.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    HeaderItem: typeof import('./src/components/HeaderItem/HeaderItem.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Logo: typeof import('./src/components/icons/Logo.vue')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('primevue/skeleton')['default']
    SwiperlItem: typeof import('./src/components/SwiperlItem/SwiperlItem.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    Toast: typeof import('primevue/toast')['default']
  }
}
