/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    ColorPicker: typeof import('primevue/colorpicker')['default']
    Drawer: typeof import('primevue/drawer')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    HeaderItem: typeof import('./src/components/HeaderItem/HeaderItem.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Logo: typeof import('./src/components/icons/Logo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
